### PR TITLE
user Rails.cache for mi ticket cache

### LINKED ISSUE #1: Use Rails.cache to store mi tickets in cache
Take a look here http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch for details.

### PR DESCRIPTION
**Pull request by mkasztelnik**
Fixes #1

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@VPH-Share/cyfronet-dev-team please take a look

**Comment by pasuder** [comment]
Looks better. I guess that [caching with Rails](http://guides.rubyonrails.org/caching_with_rails.html) is better than hand-made caching? If yes then :+1:

**Comment by mkasztelnik** [comment]
@paoolo no in all cases. E.g. I tried to use similar solution to cache cloud client. Unfortunately it serializes object into file and this is not possible for fog clients.

**Comment by mkasztelnik** [comment]
@VPH-Share/cyfronet-dev-team another review - please!!

**Comment by nowakowski** [comment]
:+1:

**Pull request merged**
