### PR TITLE
Atmo serves factories

### PR DESCRIPTION
**Pull request by mkasztelnik**
Since https://github.com/dice-cyfronet/atmosphere/pull/97 was merged into atmosphere master all specs from this project failed since factories were duplicated. This PR fixes this issue and fixes security proxy spec.

/cc @VPH-Share/cyfronet-dev-team please take a look

### CODE REVIEW

**Comment by pasuder** [comment]
Did you removed `spec` test only? In _Files changed_ I see migration from https://github.com/dice-cyfronet/atmosphere/pull/15. Did you noticed that?

**Comment by mkasztelnik** [comment]
`schema.rb` was regenerated, that is why you see migrato changes. But you are right I should remove it from this PR.

**Comment by mkasztelnik** [comment]
@paoolo done as requested - `schema.rb` changes removed from this PR.

**Comment by Nuanda** [comment]
:+1:

**Comment by pasuder** [comment]
Git master! :+1:

**Pull request merged**
