### PR TITLE
Bugfix for billing_in_deployments

### PR DESCRIPTION
**Pull request by nowakowski**
Ensures persistent assignment of OSFamily for new ApplianceTypes.

### CODE REVIEW

**Comment by mkasztelnik** [comment]
Since https://github.com/dice-cyfronet/atmosphere/pull/119 is already merged into master I changed atmosphere branch in `Gemfile` into master. What is more I merged `master` branch into this branch to apply changes required by latest atmosphere.

**Comment by mkasztelnik** [comment]
:+1:

**Comment by mkasztelnik** [comment]
@VPH-Share/cyfronet-dev-team please take a look.

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
